/*
 * Copyright 2018 NUROX Ltd.
 *
 * Licensed under the NUROX Ltd Software License (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.looseboxes.com/legal/licenses/software.html
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package com.looseboxes.msofficekiosk.ui.admin;

import javax.swing.JMenu;
import javax.swing.JMenuItem;
import javax.swing.JProgressBar;
import javax.swing.JScrollPane;
import javax.swing.JTextField;

/**
 *
 * @author Josh
 */
public class AdminFrame extends javax.swing.JFrame {

    private final AdminPanel adminPanel;
    private final JScrollPane scrolls;
    
    /**
     * Creates new form AdminFrame
     */
    public AdminFrame() {
        initComponents();
        this.adminPanel = new AdminPanel();
        this.scrolls = new JScrollPane(this.adminPanel);
        this.getContentPane().add(this.scrolls);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        messageTextField = new javax.swing.JTextField();
        progressBar = new javax.swing.JProgressBar();
        menuBar = new javax.swing.JMenuBar();
        fileMenu = new javax.swing.JMenu();
        loginMenuItem = new javax.swing.JMenuItem();
        settingsMenuItem = new javax.swing.JMenuItem();
        exitMenuItem = new javax.swing.JMenuItem();
        viewMenu = new javax.swing.JMenu();
        viewSubmittedDocsMenuItem = new javax.swing.JMenuItem();
        viewConnectedDevicesMenuItem = new javax.swing.JMenuItem();
        helpMenu = new javax.swing.JMenu();
        aboutMenuItem = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        messageTextField.setEditable(false);

        fileMenu.setMnemonic('f');
        fileMenu.setText("File");

        loginMenuItem.setText("Login");
        fileMenu.add(loginMenuItem);

        settingsMenuItem.setText("Settings");
        fileMenu.add(settingsMenuItem);

        exitMenuItem.setMnemonic('x');
        exitMenuItem.setText("Exit");
        fileMenu.add(exitMenuItem);

        menuBar.add(fileMenu);

        viewMenu.setMnemonic('e');
        viewMenu.setText("View");

        viewSubmittedDocsMenuItem.setMnemonic('t');
        viewSubmittedDocsMenuItem.setText("Received Docus");
        viewMenu.add(viewSubmittedDocsMenuItem);

        viewConnectedDevicesMenuItem.setMnemonic('y');
        viewConnectedDevicesMenuItem.setText("Connected Devices");
        viewMenu.add(viewConnectedDevicesMenuItem);

        menuBar.add(viewMenu);

        helpMenu.setMnemonic('h');
        helpMenu.setText("Help");

        aboutMenuItem.setMnemonic('a');
        aboutMenuItem.setText("About");
        helpMenu.add(aboutMenuItem);

        menuBar.add(helpMenu);

        setJMenuBar(menuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(messageTextField, javax.swing.GroupLayout.DEFAULT_SIZE, 350, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(progressBar, javax.swing.GroupLayout.DEFAULT_SIZE, 244, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(messageTextField)
                    .addComponent(progressBar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(0, 334, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem aboutMenuItem;
    private javax.swing.JMenuItem exitMenuItem;
    private javax.swing.JMenu fileMenu;
    private javax.swing.JMenu helpMenu;
    private javax.swing.JMenuItem loginMenuItem;
    private javax.swing.JMenuBar menuBar;
    private javax.swing.JTextField messageTextField;
    private javax.swing.JProgressBar progressBar;
    private javax.swing.JMenuItem settingsMenuItem;
    private javax.swing.JMenuItem viewConnectedDevicesMenuItem;
    private javax.swing.JMenu viewMenu;
    private javax.swing.JMenuItem viewSubmittedDocsMenuItem;
    // End of variables declaration//GEN-END:variables

    public JMenuItem getAboutMenuItem() {
        return aboutMenuItem;
    }

    public JMenuItem getViewConnectedDevicesMenuItem() {
        return viewConnectedDevicesMenuItem;
    }

    public JMenuItem getViewSubmittedDocsMenuItem() {
        return viewSubmittedDocsMenuItem;
    }

    public JMenuItem getExitMenuItem() {
        return exitMenuItem;
    }

    public JMenu getFileMenu() {
        return fileMenu;
    }

    public JMenu getHelpMenu() {
        return helpMenu;
    }

//    public JMenuBar getMenuBar() {
//        return menuBar;
//    }

    public JMenu getViewMenu() {
        return viewMenu;
    }

    public JMenuItem getSettingsMenuItem() {
        return settingsMenuItem;
    }

    public AdminPanel getAdminPanel() {
        return adminPanel;
    }

    public JScrollPane getScrolls() {
        return scrolls;
    }

    public JTextField getMessageTextField() {
        return messageTextField;
    }

    public JProgressBar getProgressBar() {
        return progressBar;
    }

    public JMenuItem getLoginMenuItem() {
        return loginMenuItem;
    }
}
